version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Explicit Node.js 20 (stable for React 19/TypeScript)
    commands:
      - echo "Cleaning cache and installing dependencies..."
      - rm -rf node_modules package-lock.json  # Clear old dependencies
      - npm install typescript --save-dev       # Install TypeScript locally
      - npm install                            # Install all dependencies

  build:
    commands:
      - echo "Checking TypeScript installation..."
      - npx tsc --version                       # Verify TypeScript is accessible
      - echo "Building React app..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'  
  base-directory: dist  # Use 'build' if using Create React App