version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Explicitly use Node.js 20 (avoid "latest")
    commands:
      - echo "Installing dependencies..."
      - npm install typescript --save-dev  # Install TypeScript locally
      - npm install

  build:
    commands:
      - echo "Checking TypeScript installation..."
      - npx tsc --version  # Verify `tsc` is accessible
      - npm run build

  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'
  base-directory: dist